---
name: C4
author: TonyDroidd
api: 1.12.0
description: A simple plugin that add C4 to your server
version: 1.1
main: TDroidd\C4\Main

commands:
    boom:
        permission: c4.boom
        default: op